<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /api/schema/</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style>
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font-family: sans-serif; background:#eee; color:#000; }
    body > :where(header, main, footer) { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 small { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
  </style>
</head>
<body>
  <header id="summary">
    <h1>Page not found <small>(404)</small></h1>
    
    <table class="meta">
      <tr>
        <th scope="row">Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th scope="row">Request URL:</th>
        <td>http://justklick-backend-kjrdc8-2f68d5-162-35-161-160.sslip.io/api/schema/</td>
      </tr>
      
    </table>
  </header>

  <main id="info">
    
      <p>
      Using the URLconf defined in <code>config.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
              <code>
                admin/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                admin-login/
                [name='admin_login']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                forgot-password/
                [name='forgot_password']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                reset-password/&lt;uidb64&gt;/&lt;token&gt;/
                [name='reset_password']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                logout/
                [name='logout']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                vendor/register/
                [name='vendor-register']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                vendor/login/
                [name='vendor-login']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                admin-leads/
                [name='admin-leads']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                delete/&lt;int:pk&gt;/
                [name='delete']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                trash/
                [name='trash']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                restore/&lt;int:pk&gt;/
                [name='restore']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                lead/permanent-delete/&lt;int:pk&gt;/
                [name='permanent-delete']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                admin-reviews/
                [name='admin-reviews']
              </code>
            
          </li>
        
          <li>
            
              <code>
                logout/
                [name='logout']
              </code>
            
          </li>
        
          <li>
            
              <code>
                dashboard/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                dashboard/categories/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                dashboard/businesses/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                vendor/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                openapi.json
                [name='openapi-json']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                docs
                [name='openapi-view']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                google-auth
                [name='google_auth_verify']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                register/send-otp
                [name='register_send_otp']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                register/verify-otp
                [name='register_verify_otp']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                login/send-otp
                [name='login_send_otp']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                login/verify-otp
                [name='login_verify_otp']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                resend-otp
                [name='resend_otp_view']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                send-email-login-otp
                [name='send_email_login_otp']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-register
                [name='register']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-register
                [name='student_register_page']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-login
                [name='login']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-login
                [name='student_login_page']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dashboard
                [name='dashboard']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-onboarding
                [name='student_onboarding']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-profile
                [name='student_profile']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-profile-update
                [name='update_student_profile']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                submit-lead
                [name='submit_lead']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                student-logout
                [name='student_logout']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                advertisements/active/
                [name='list_active_advertisements']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/save-device-token
                [name='save_device_token']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/send-login-push
                [name='send_login_push']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/send
                [name='send_notification']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/list
                [name='list_notifications']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/&lt;notification_id&gt;/mark-read
                [name='mark_notification_read']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                notifications/mark-all-read
                [name='mark_all_notifications_read']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                categories/
                [name='list_categories']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                businesses/
                [name='list_businesses']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                businesses/locations/search/
                [name='search_locations']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                businesses/&lt;slug&gt;/
                [name='get_business']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                vendors/reviews
                [name='create_review']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                vendors/business/&lt;business_id&gt;/reviews
                [name='business_reviews']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/why-choose-us/
                [name='why_choose_us_list']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/faqs/
                [name='faq_list']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/about
                [name='homepage']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/contact-page
                [name='contact_page']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/contact-submit
                [name='contact_submit']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/contact-enquiries
                [name='contact_enquiries']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                dynamic/tourist-places/
                [name='tourist_places']
              </code>
            
          </li>
        
          <li>
            
              <code>
                api/
                
              </code>
            
              <code>
                
                [name='api-root']
              </code>
            
          </li>
        
          <li>
            
              <code>
                advertisements/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                dashboard/dynamic/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                ^media/(?P&lt;path&gt;.*)$
                
              </code>
            
          </li>
        
      </ol>
      <p>
        
          The current path, <code>api/schema/</code>,
        
        didn’t match any of these.
      </p>
    
  </main>

  <footer id="explanation">
    <p>
      You’re seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </footer>
</body>
</html>
